ANGOLASUP-825: Fixed inventory saving functionality
OpenLMIS-Angola/angola-ui pull request #32
Opened 2023-06-13 07:45 UTC by sradziszewski

Added functionality for caching products added with a new lot code.

JIRA task link: https://openlmis.atlassian.net/browse/ANGOLASUP-825

2023-06-13 09:00 UTC, dariapionk reviewed
when we add comments like '// ANGOLASUP-825: ' there is no need to clarify what exactly hapenned in specific scope
You can change all of commented lines to 'ANGOLASUP-825: Fixed inventory saving functionality' (same as title of your PR)
The rest looks good to me

2023-06-14 08:29 UTC, kmadej commented
@sradziszewski please apply Daria's comment

2023-06-15 09:19 UTC, kmadej requested changes

2023-06-15 09:19 UTC, kmadej commented on src/stock-edit-lot-modal/edit-lot-modal.service.js
> +        // ANGOLASUP-825: Changed function parameters from item list to draft
changed this comment also

2023-06-15 09:24 UTC, sradziszewski commented on src/stock-edit-lot-modal/edit-lot-modal.service.js
> +        // ANGOLASUP-825: Changed function parameters from item list to draft
comment changed

2023-06-15 09:26 UTC, dariapionk approved these changes

2023-06-15 09:26 UTC, kmadej commented
@sradziszewski looks good to me, @dariapionk please merge

2023-06-15 09:26 UTC, merged